name: GuestBook CI/CD Pipeline

on: [ push]

jobs:
  ci-job:
    runs-on: ubuntu-latest

    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 3.34.49.129
        username: ec2-user
        key: ${{ secrets.STAGING_PRIVATE_KEY }}
        port: 22
        script: |
          id
          hostnamectl